### ISSUE TITLE
CMake and Travis intro

### ISSUE THREAD

**Issue by SergiusTheBest** [SergiusTheBest/RevJay-s-study#3]
# CMake
1. What is CMake?
1. What OS and generators does it support?
1. Install CMake.
1. Create a HelloWorld CMake sample application. Commit it to a new github repo.
1. Build the sample using Visual Studio.

# Travis
1. What is CI (continuous integration)?
1. What is Travis CI?
1. What languages does it support? Is it free?
1. Set up automatic builds for the HelloWorld CMake sample application:
  * Trigger a new build after a commit to the repo.
  * Build using gcc and clang on linux.
  * Run the application after a build.
  * Place a badge (build status image) into a readme file so it can be viewed online.

**Comment by RevJay** [comment]
**CMake**
1. What is CMake?
CMake is an extensible, cross-platform open-source system, which manages the build process in an operating system and in compiler-independent manner. It is used to control the software compilation process using simple platform and compiler independent configuration files, generates native makefiles and workspaces.

2. What OS and generators does it support?
Generators: Borland MakeFiles, MinGW Makefiles, Ninja, Visual Studio 6-12, Xcode, Codelite, Eclipse, Sublime Text2.
Operating systems:
Linux, Microsoft Windows and Mac OS X.

3. Install CMake.
Installed.

4. Create a HelloWorld CMake sample application. Commit it to a new github repo.
5. Build the sample using Visual Studio.
4-5. My new repo with Cmake sample application: https://github.com/RevJay/cmake_travis

**Travis**
1. What is CI (continuous integration)? 
Continuous Integration is a software development practice where members of a team integrate their work frequently, usually each person integrates at least daily - leading to multiple integrations per day. Each integration is verified by an automated build (including test) to detect integration errors as quickly as possible. Many teams find that this approach leads to significantly reduced integration problems and allows a team to develop cohesive software more rapidly.

2. What is Travis CI? 
Travis CI is a hosted (on Github) continuous integration and deployment system.

3. What languages does it support? Is it free?
It is free for open (Github repositories) source projects. Travis CI supports C, C++, D, JavaScript, Java, PHP, Python и Ruby.

4. To be continued...)

**Comment by SergiusTheBest** [comment]
This directory is autogenerated and shouldn't be in the repository: https://github.com/RevJay/cmake_travis/tree/master/hellocmake/src/build

**Comment by RevJay** [comment]
New repository without autogenerated directory (build) and task 4 (automatic builds with Travis CI) https://github.com/RevJay/hellocmake

**Comment by SergiusTheBest** [comment]
The script doesn't build anything. Take a look at https://github.com/SergiusTheBest/plog/blob/master/.travis.yml

**Comment by SergiusTheBest** [comment]
Ok.
